# Generated by Django 6.0.6 on 2026-06-18 17:56

import customers.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=customers.models.EncryptedEmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=customers.models.EncryptedCharField(max_length=255),
        ),
    ]
