# Generated by Django 6.0.6 on 2026-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_checkout_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('M-Pesa STK', 'M-Pesa STK'), ('Payment Link', 'Payment Link')], default='M-Pesa STK', max_length=50),
        ),
    ]
