# Generated by Django 6.0.6 on 2026-07-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payment_link_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deposit_type',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Partial Payment', 'Partial Payment'), ('Final Payment', 'Final Payment'), ('Full Payment', 'Full Payment')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('M-Pesa STK', 'M-Pesa STK'), ('Payment Link', 'Payment Link'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='M-Pesa STK', max_length=50),
        ),
    ]
