# Generated by Django 6.0.6 on 2026-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_subscription_end_date_subscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_currency',
            field=models.CharField(default='KSh', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
