# Generated by Django 6.0.6 on 2026-07-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinged_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='alive', max_length=20)),
            ],
            options={
                'verbose_name': 'Database Heartbeat',
                'verbose_name_plural': 'Database Heartbeats',
                'db_table': 'core_database_heartbeat',
            },
        ),
    ]
